-- Production-ready Supabase schema for Refad IoT Cloud
-- Includes Supabase Auth compatibility, Row Level Security, secure policies,
-- optimized telemetry indexes, and strong relationships for multi-tenant SaaS.

create extension if not exists pgcrypto;

-- ============================================================================
-- STEP 1: Create all tables in dependency order
-- ============================================================================

-- Core organization table (no dependencies).
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.organizations is 'Tenant organization metadata for multi-tenant IoT deployments.';
comment on column public.organizations.owner_id is 'Supabase Auth user ID that owns the organization.';

-- App-specific user profile table linked to Supabase Auth users.
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  display_name text,
  role text not null default 'member',
  org_id uuid not null references public.organizations(id) on delete cascade,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.users is 'Application user profiles linked to Supabase Auth users.';
comment on column public.users.role is 'Role-based access control: owner, admin, member.';

-- Device registry.
create table if not exists public.devices (
  id text primary key,
  name text not null,
  type text not null,
  status text not null default 'online',
  org_id uuid not null references public.organizations(id) on delete cascade,
  last_seen timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.devices is 'Registered IoT devices for each tenant organization.';

-- Grouping for devices.
create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.groups is 'Logical device groups and team structures per organization.';

-- Many-to-many relationship between groups and devices.
create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  device_id text not null references public.devices(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (group_id, device_id)
);

comment on table public.group_members is 'Many-to-many relationship between groups and devices.';

-- Telemetry table optimized for high-frequency IoT ingest and query.
create table if not exists public.telemetry (
  id bigserial primary key,
  device_id text not null references public.devices(id) on delete cascade,
  temperature double precision,
  humidity double precision,
  battery_level smallint,
  signal_strength smallint,
  status text not null default 'ok',
  payload jsonb not null default '{}'::jsonb,
  reported_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

comment on table public.telemetry is 'Time-series IoT telemetry captured from devices.';
comment on column public.telemetry.payload is 'Raw telemetry payload for flexible sensor fields.';

-- Command queue for device actions.
create table if not exists public.commands (
  id bigserial primary key,
  device_id text not null references public.devices(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  command text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.commands is 'Commands queued for device execution with status tracking.';

-- Alerts generated by telemetry rules and device state.
create table if not exists public.alerts (
  id bigserial primary key,
  device_id text not null references public.devices(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  level text not null default 'warning',
  message text not null,
  details jsonb not null default '{}'::jsonb,
  acknowledged boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.alerts is 'Alert events created by rules engine or manual device evaluation.';

-- System and audit logs for device events and platform actions.
create table if not exists public.logs (
  id bigserial primary key,
  device_id text not null references public.devices(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  level text not null default 'info',
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.logs is 'Event logs for device activity and platform diagnostics.';

-- ============================================================================
-- STEP 2: Create indexes for performance
-- ============================================================================

create index if not exists telemetry_device_timestamp_idx on public.telemetry (device_id, reported_at desc);
create index if not exists telemetry_reported_at_idx on public.telemetry (reported_at desc);
create index if not exists telemetry_payload_idx on public.telemetry using gin (payload jsonb_path_ops);
create index if not exists devices_org_idx on public.devices (org_id);
create index if not exists commands_org_device_idx on public.commands (org_id, device_id, created_at desc);
create index if not exists alerts_org_created_idx on public.alerts (org_id, created_at desc);
create index if not exists logs_org_created_idx on public.logs (org_id, created_at desc);
create index if not exists group_members_group_idx on public.group_members (group_id);
create index if not exists group_members_device_idx on public.group_members (device_id);

-- ============================================================================
-- STEP 3: Enable Row Level Security on all tenant-scoped tables
-- ============================================================================

alter table public.organizations enable row level security;
alter table public.users enable row level security;
alter table public.devices enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.telemetry enable row level security;
alter table public.commands enable row level security;
alter table public.alerts enable row level security;
alter table public.logs enable row level security;

-- ============================================================================
-- STEP 4: Create helper functions for RLS policies
-- ============================================================================

create or replace function public.current_user_id()
returns uuid stable language sql security definer as $$
  select auth.uid();
$$;

create or replace function public.current_user_org_id()
returns uuid stable language sql security definer as $$
  select org_id from public.users where id = auth.uid();
$$;

-- ============================================================================
-- STEP 5: Create all RLS policies
-- ============================================================================

-- Policies for organizations table
drop policy if exists org_select_policy on public.organizations;
create policy org_select_policy on public.organizations
  for select using (
    auth.role() = 'authenticated' and owner_id = auth.uid()
  );

-- Policies for users table
drop policy if exists user_self_select on public.users;
create policy user_self_select on public.users
  for select using (id = auth.uid());

drop policy if exists user_self_update on public.users;
create policy user_self_update on public.users
  for update using (id = auth.uid());

drop policy if exists user_owner_insert on public.users;
create policy user_owner_insert on public.users
  for insert with check (id = auth.uid());

-- Policies for devices table
drop policy if exists device_org_select on public.devices;
create policy device_org_select on public.devices
  for select using (org_id = public.current_user_org_id());

drop policy if exists device_org_modify on public.devices;
create policy device_org_modify on public.devices
  for insert with check (org_id = public.current_user_org_id());

drop policy if exists device_org_update on public.devices;
create policy device_org_update on public.devices
  for update using (org_id = public.current_user_org_id()) with check (org_id = public.current_user_org_id());

-- Policies for groups table
drop policy if exists group_org_select on public.groups;
create policy group_org_select on public.groups
  for select using (org_id = public.current_user_org_id());

drop policy if exists group_org_modify on public.groups;
create policy group_org_modify on public.groups
  for insert with check (org_id = public.current_user_org_id());

drop policy if exists group_org_update on public.groups;
create policy group_org_update on public.groups
  for update using (org_id = public.current_user_org_id()) with check (org_id = public.current_user_org_id());

-- Policies for group_members table
drop policy if exists group_member_select on public.group_members;
create policy group_member_select on public.group_members
  for select using (
    exists(
      select 1 from public.groups g
      where g.id = group_id and g.org_id = public.current_user_org_id()
    )
  );

-- Policies for telemetry table
drop policy if exists telemetry_org_select on public.telemetry;
create policy telemetry_org_select on public.telemetry
  for select using (
    exists(
      select 1 from public.devices d
      where d.id = device_id and d.org_id = public.current_user_org_id()
    )
  );

-- Policies for commands table
drop policy if exists command_org_select on public.commands;
create policy command_org_select on public.commands
  for select using (org_id = public.current_user_org_id());

drop policy if exists command_org_modify on public.commands;
create policy command_org_modify on public.commands
  for insert with check (org_id = public.current_user_org_id());

drop policy if exists command_org_update on public.commands;
create policy command_org_update on public.commands
  for update using (org_id = public.current_user_org_id()) with check (org_id = public.current_user_org_id());

-- Policies for alerts table
drop policy if exists alert_org_select on public.alerts;
create policy alert_org_select on public.alerts
  for select using (org_id = public.current_user_org_id());

drop policy if exists alert_org_modify on public.alerts;
create policy alert_org_modify on public.alerts
  for insert with check (org_id = public.current_user_org_id());

-- Policies for logs table
drop policy if exists log_org_select on public.logs;
create policy log_org_select on public.logs
  for select using (org_id = public.current_user_org_id());

drop policy if exists log_org_modify on public.logs;
create policy log_org_modify on public.logs
  for insert with check (org_id = public.current_user_org_id());

-- ============================================================================
-- STEP 6: Create triggers for automatic updated_at timestamp
-- ============================================================================

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();

drop trigger if exists devices_set_updated_at on public.devices;
create trigger devices_set_updated_at before update on public.devices for each row execute function public.set_updated_at();

drop trigger if exists groups_set_updated_at on public.groups;
create trigger groups_set_updated_at before update on public.groups for each row execute function public.set_updated_at();

drop trigger if exists commands_set_updated_at on public.commands;
create trigger commands_set_updated_at before update on public.commands for each row execute function public.set_updated_at();

drop trigger if exists alerts_set_updated_at on public.alerts;
create trigger alerts_set_updated_at before update on public.alerts for each row execute function public.set_updated_at();

-- ============================================================================
-- End of schema. Service role key can bypass all RLS policies.
-- ============================================================================
